### ISSUE TITLE
To open incognito window

### ISSUE THREAD

**Issue by akshay31057** [ContriHUB/Chrome-It#10]

**Comment by ardlank** [comment]
I can help. Please assign to me.

**Comment by akshay31057** [comment]
Hi @ardlank , 
Thanks for your interest in resolving the issue. Actually, we have opened these issues for the beginners of our college to help them learn during the hacktoberfest. So, I can't assign this issue to you. Thanks.

**Comment by roopbiswas** [comment]
Sir , I would like to work on this issue. Please assign this issue to me.

**Comment by sanyamsinghal** [comment]
sir, I am working on this issue
