### ISSUE TITLE
To perform functionality of back button.

### ISSUE THREAD

**Issue by akshay31057** [ContriHUB/Chrome-It#11]

**Comment by Thilagavathi1** [comment]
@akshay31057  I would to like to do this ,can you tell me where you need to implement 
this?

**Comment by akshay31057** [comment]
Hi @Thilagavathi1, 
Thanks for your interest in resolving the issue. Actually, we have opened these issues for the beginners of our college to help them learn during the hacktoberfest. So, I can't assign this issue to you. Thanks.

**Comment by Thilagavathi1** [comment]
Cool

**Comment by roopbiswas** [comment]
Sir , I would like to work on this issue.
