### ISSUE TITLE
Add code for moving to tab to immediate left

### ISSUE THREAD

**Issue by akshay31057** [ContriHUB/Chrome-It#15]

**Comment by shreeshylahs** [comment]
when you say moving to tab to immediate left, do you mean the **browser tab** or the **tab inside app**?

**Comment by akshay31057** [comment]
Browser tab

**Comment by kunalmnnit** [comment]
Sir,I would be working on the issue

**Comment by suraj-goel** [comment]
Sir,I would like to work on this issue.
Please assign me this issue.
