### ISSUE TITLE
Implement provideJoke() function to return a joke

### ISSUE THREAD

**Issue by akshay31057** [ContriHUB/Chrome-It#19]

**Comment by NischalJakhar** [comment]
Please provide description on this-->Pick a joke from where? Using an Api to return random jokes || Local variables

**Comment by ayush987goyal** [comment]
Where do you want this function implemented?

**Comment by roopbiswas** [comment]
Sir, I would like to work on this issue.

**Comment by akshay31057** [comment]
@ayush987goyal @NischalJakhar  Thanks for showing interest in our repository. But we have created this repository for those students in our college who are a beginner in the world of Open Source Software Development. So, we can't assign this issue to you.

**Comment by akshay31057** [comment]
@roopbiswas You have been assigned this issue. You have to update your progress within the next 3 days that is, before 11/10/18 (included).
