### ISSUE TITLE
Add functionality to change body background color

### ISSUE THREAD

**Issue by akshay31057** [ContriHUB/Chrome-It#3]

**Comment by Thilagavathi1** [comment]
@akshay31057 i like to do this task,can you provide me how to run this application and need detail information about the task.

**Comment by Thilagavathi1** [comment]
@akshay31057 can u provide me brief information about this functionality

**Comment by sanyamsinghal** [comment]
Sir, I want to work on this issue so please assign this to me.

**Comment by sanyamsinghal** [comment]
sir can u provide some description for this issue.

**Comment by akshay31057** [comment]
When the user says "Change background blue" then the body background colour changes to blue.
