### ISSUE TITLE
Print the current tab using voice command

### ISSUE THREAD

**Issue by akshay31057** [ContriHUB/Chrome-It#5]

**Comment by bhonesh1998** [comment]
Sir,what does it mean ?

**Comment by hiiiideepak** [comment]
> Sir,what does it mean ?

It means you have to implement ctrl+p on current page using voice :smile:

**Comment by bhonesh1998** [comment]
> > Sir,what does it mean ?
> 
> It means you have to implement ctrl+p on current page using voice

thanks!

**Comment by roopbiswas** [comment]
Sir, I am working on this issue.
